services:
  dbdevelopment:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: senha0
    ports:
      - "5433:5432"
    networks:
      - emiratads-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - emiratads-network

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASSWORD}
    networks:
      - emiratads-network

  sagaorchestrator:
    build:
      context: ./backend/saga-orchestration-service
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
      - "5004:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - rabbitmq
    networks:
      - emiratads-network

  autenticacaoservice:
    platform: linux/amd64
    build:
      context: ./backend/autenticacao-service
      dockerfile: ../Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
      EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
      SECRET_API_KEY: ${SECRET_API_KEY}
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - emiratads-network

  clienteservice:
    build:
      context: ./backend/cliente-service
      dockerfile: ../Dockerfile
    ports:
      - "8082:8080"
      - "5006:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - emiratads-network

  funcionarioservice:
    build:
      context: ./backend/funcionario-service
      dockerfile: ../Dockerfile
    ports:
      - "8083:8080"
      - "5007:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - emiratads-network

  reservaservice:
    build:
      context: ./backend/reserva-service
      dockerfile: ../Dockerfile
    ports:
      - "8084:8080"
      - "5008:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - emiratads-network

  vooservice:
    build:
      context: ./backend/voo-service
      dockerfile: ../Dockerfile
    ports:
      - "8085:8080"
      - "5009:5005"
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
    networks:
      - emiratads-network

  apigateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      SECRET_API_KEY: ${SECRET_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      SAGA_ORCHESTRATOR_URL: ${SAGA_ORCHESTRATOR_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      CLIENTE_SERVICE_URL: ${CLIENTE_SERVICE_URL}
      FUNCIONARIO_SERVICE_URL: ${FUNCIONARIO_SERVICE_URL}
      RESERVA_SERVICE_URL: ${RESERVA_SERVICE_URL}
      VOO_SERVICE_URL: ${VOO_SERVICE_URL}
    depends_on:
      - sagaorchestrator
      - autenticacaoservice
      - funcionarioservice
      - reservaservice
      - vooservice
    networks:
      - emiratads-network

networks:
  emiratads-network:
    driver: bridge