services:
  dbdevelopment:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: senha0
    networks:
      - private-network

  mongodb:
    image: mongo
    restart: always
    networks:
      - private-network

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASSWORD}
    networks:
      - private-network

  sagaorchestrator:
    image: salgado2004/dac-ufpr-emiratads-saga-orchestration-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - rabbitmq
    networks:
      - private-network

  autenticacaoservice:
    image: salgado2004/dac-ufpr-emiratads-autenticacao-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
      EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
      SECRET_API_KEY: ${SECRET_API_KEY}
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - private-network

  clienteservice:
    image: salgado2004/dac-ufpr-emiratads-cliente-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - private-network

  funcionarioservice:
    image: salgado2004/dac-ufpr-emiratads-funcionario-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - private-network

  reservaservice:
    image: salgado2004/dac-ufpr-emiratads-reserva-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - private-network

  vooservice:
    image: salgado2004/dac-ufpr-emiratads-voo-service
    environment:
      GATEWAY_URL: ${GATEWAY_URL}
    depends_on:
      - autenticacaoservice
      - dbdevelopment
    networks:
      - private-network

  apigateway:
    image: salgado2004/dac-ufpr-emiratads-gateway
    ports:
      - "3030:3030"
    depends_on:
      - sagaorchestrator
      - autenticacaoservice
      - funcionarioservice
      - reservaservice
      - vooservice
    networks:
      - private-network
      - public-network    
    env_file:
      - .env

  frontend:
    image: salgado2004/dac-ufpr-emiratads-frontend
    ports:
      - "3000:3000"
    depends_on:
      - apigateway
    environment:
      NEXT_PUBLIC_BASE_URL: ${GATEWAY_URL}/api/v1
    networks:
      - public-network

networks:
  private-network:
    driver: bridge
  public-network:
    driver: bridge