services:
  dbdevelopment:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: senha0
    ports:
      - "5433:5432"
    networks:
      - emiratads-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - emiratads-network

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    networks:
      - emiratads-network

  sagaorchestrator:
    build:
      context: ./saga-orchestration-service
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - emiratads-network

  autenticacaoservice:
    platform: linux/amd64
    build:
      context: ./autenticacao-service
      dockerfile: ../Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - emiratads-network

  clienteservice:
    build:
      context: ./cliente-service
      dockerfile: ../Dockerfile
    ports:
      - "8082:8080"
      - "5006:5005"
    depends_on:
      - autenticacaoservice
      - dbdevelopment
      - rabbitmq
    networks:
      - emiratads-network

  funcionarioservice:
    image: salgado2004/dac-ufpr-emiratads-funcionario-service
    ports:
      - "8083:8080"
    depends_on:
      - autenticacaoservice
      - dbdevelopment
    networks:
      - emiratads-network

  reservaservice:
    build:
      context: ./reserva-service
      dockerfile: ../Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - autenticacaoservice
      - dbdevelopment
    networks:
      - emiratads-network

  vooservice:
    build:
      context: ./voo-service
      dockerfile: ../Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - autenticacaoservice
      - dbdevelopment
    networks:
      - emiratads-network

networks:
  emiratads-network:
    driver: bridge