services:
  autenticacaoservice:
    build:
      context: ./autenticacao-service
      dockerfile: ../Dockerfile
    ports:
      - "8081:8080"

  clienteservice:
    build:
      context: ./cliente-service
      dockerfile: ../Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - autenticacaoservice

  funcionarioservice:
    image: salgado2004/dac-ufpr-emiratads-funcionario-service
    ports:
      - "8083:8080"
    depends_on:
      - autenticacaoservice

  reservaservice:
    build:
      context: ./reserva-service
      dockerfile: ../Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - autenticacaoservice

  vooservice:
    build:
      context: ./voo-service
      dockerfile: ../Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - autenticacaoservice