spring:
  application:
    name: autenticacao-service
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: mongodb
      port: 27017
api:
  security:
    token:
      secret: 12345678