services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - emiratads-network

  autenticacaoservice:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - emiratads-network

networks:
  emiratads-network:
    driver: bridge